version: '3'

services:
  kv-server:
    build: 
      context: ./web-service
      dockerfile: Dockerfile-server
    depends_on: 
      - "ocypod" 
    #ports:
    #  - 8081:8081


  kv-worker:
    build: 
      context: ./web-service
      dockerfile: Dockerfile-worker
    depends_on: 
      - "ocypod"  
    volumes:
      - kvfinder-jobs:/jobs


  ocypod:
    image: davechallis/ocypod:latest
    volumes:
      - ./queue/ocypod.toml:/etc/ocypod.toml:z
    depends_on: 
      - "ocypod-redis"
    command: /etc/ocypod.toml
    # ports:
      # - 8023:8023

  ocypod-redis:
    image: redis:6
    # ports:
    #   - 6379:6379
    volumes:
      - ocypod-redis-data:/data

  kvshiny:
    build:
      context: ../KVshiny-docker
    depends_on:
      - "kv-server"
    #ports:
    # - 8080:3838

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - "kvshiny"
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/certs/.well-known:/usr/share/caddy/.well-known
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
      - caddy_data:/data
      - caddy_config:/config

volumes:
  ocypod-redis-data:
    driver: local
  kvfinder-jobs:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
   
networks:
  kvfinder-web-service_default:
    external: true
